const candys = [
"Chilli Milli",
"Imli Jelly",
"Coconut Toffee",
"Blueberry Toffee",
"Cola Toffee",
"Almond Toffee",
"Kacha Aam Toffee",
"Bubblegum Jelly",
"Mint Blast",
"Kacha Aam Jelly",
"Tutti Frutti",
"Super Sour",
"Caramel Crunch",
"Eclairs Classic",
"Churan Chatni",
"Coconut Jelly",
"Cola Bottles",
"Pan Pasand Toffee",
"Fruit Rings",
"Softmint",
"Imli Toffee",
"Butterscotch Toffee",
"Pizza Jelly",
"Fanty" ,
];